// Name: images include file
// License: Public Domain
// Author: Christopher Bennett
// Description: Dictionaries of parameters for loading images.  
//              Used in loadImage() function in settings.inc.


// Sirius is the brightest star in the constellation Canis Major.
alf_CMa = {
    id: "alf_CMa",
    path: "../images/alf_CMa.png",
    ra: "6h 45m 08.0s",
    dec: "-16d 43m 30.0s",
    angSize: 1.5, // arcminutes
    rotation: 0,  // degrees
    minRes: 2.5,
    maxBright: 14,
    visible: false
};

// Procyon is the brightest star in the constellation Canis Minor.
alf_CMi = {
    id: "alf_CMi",
    path: "../images/alf_CMi.png",
    ra: "7h 39m 17.0s",
    dec: "+5d 12m 57.4s",
    angSize: 1.5, // arcminutes
    rotation: 0,  // degrees
    minRes: 2.5,
    maxBright: 14,
    visible: false
};

